package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/Plebysnacc/kummerkasten/auth"
	"github.com/Plebysnacc/kummerkasten/graph/model"
	"github.com/google/uuid"
	"github.com/uptrace/bun"
)

// CreateTicket is the resolver for the createTicket field.
func (r *mutationResolver) CreateTicket(ctx context.Context, ticket model.NewTicket) (*model.Ticket, error) {
	insertedTicket := &model.Ticket{
		ID:           uuid.New().String(),
		Text:         ticket.Text,
		Title:        ticket.Title,
		State:        model.TicketState(ticket.State),
		CreatedAt:    time.Now(),
		LastModified: time.Now(),
	}

	if _, err := r.DB.NewInsert().Model(insertedTicket).Exec(ctx); err != nil {
		log.Printf("Failed to create Ticket: %v", err)
		return nil, err
	}

	return insertedTicket, nil
}

// DeleteTicket is the resolver for the deleteTicket field.
func (r *mutationResolver) DeleteTicket(ctx context.Context, id []string) (string, error) {
	panic(fmt.Errorf("not implemented: DeleteTicket - deleteTicket"))
}

// UpdateTicket is the resolver for the updateTicket field.
func (r *mutationResolver) UpdateTicket(ctx context.Context, id string, ticket model.NewTicket) (*model.Ticket, error) {
	panic(fmt.Errorf("not implemented: UpdateTicket - updateTicket"))
}

// UpdateTicketState is the resolver for the updateTicketState field.
func (r *mutationResolver) UpdateTicketState(ctx context.Context, id []string, state model.TicketState) (string, error) {
	panic(fmt.Errorf("not implemented: UpdateTicketState - updateTicketState"))
}

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, label model.NewLabel) (*model.Label, error) {
	insertedLabel := &model.Label{
		Name:    label.Name,
		Color:   label.Color,
		Tickets: make([]*model.Ticket, 0),
	}

	if _, err := r.DB.NewInsert().Model(insertedLabel).Exec(ctx); err != nil {
		log.Printf("Failed to create label: %v", err)
		return nil, err
	}

	return insertedLabel, nil
}

// DeleteLabel is the resolver for the deleteLabel field.
func (r *mutationResolver) DeleteLabel(ctx context.Context, id []int32) (int32, error) {
	panic(fmt.Errorf("not implemented: DeleteLabel - deleteLabel"))
}

// UpdateLabel is the resolver for the updateLabel field.
func (r *mutationResolver) UpdateLabel(ctx context.Context, label model.NewLabel) (*model.Label, error) {
	panic(fmt.Errorf("not implemented: UpdateLabel - updateLabel"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, user model.NewUser) (*model.User, error) {
	sid, _ := auth.GenerateSID()

	hashedPassword, err := auth.HashPassword(user.Password)

	if err != nil {
		log.Printf("Failed to create user")
	}

	newUser := &model.User{
		ID:           uuid.New().String(),
		Sid:          sid,
		Mail:         user.Mail,
		Firstname:    user.Firstname,
		Lastname:     user.Lastname,
		Password:     hashedPassword,
		Role:         model.UserRoleUser,
		CreatedAt:    time.Now(),
		LastModified: time.Now(),
	}

	if _, err := r.DB.NewInsert().Model(newUser).Exec(ctx); err != nil {
		log.Printf("Failed to create user: %v", err)
		return nil, err
	}

	return newUser, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, ids []string) (int32, error) {
	if len(ids) == 0 {
		return 0, fmt.Errorf("no ids provided to DeleteUser()")
	}

	result, err := r.DB.NewDelete().Model((*model.User)(nil)).Where("ID IN (?)", bun.In(ids)).Exec(ctx)

	if err != nil {
		log.Printf("Failed to delete user: %v", err)
		return 0, err
	}

	rowsAffected, _ := result.RowsAffected()
	return int32(rowsAffected), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, user model.UpdateUser) (string, error) {
	users, err := r.Query().Users(ctx, []string{id}, make([]string, 0), nil)

	if err != nil || len(users) == 0 {
		return "", fmt.Errorf("user with id %v not found", id)
	}

	updatedUser := users[0]

	if user.Mail != nil {
		updatedUser.Mail = *user.Mail
	}
	if user.Firstname != nil {
		updatedUser.Firstname = *user.Firstname
	}
	if user.Lastname != nil {
		updatedUser.Lastname = *user.Lastname
	}
	if user.Password != nil {
		hashedPassword, err := auth.HashPassword(*user.Password)

		if err != nil {
			log.Printf("Failed to create user: %v", err)
			return "", err
		}

		updatedUser.Password = hashedPassword
	}
	if user.Role != nil {
		updatedUser.Role = *user.Role
	}
	if user.Sid != nil {
		updatedUser.Sid = *user.Sid
	}

	updatedUser.LastModified = time.Now()

	if _, err := r.DB.NewUpdate().Model(updatedUser).
		Where("id = ?", id).
		Exec(ctx); err != nil {
		log.Printf("Failed to update user: %v", err)
		return "", err
	}

	return updatedUser.Sid, nil
}

// CreateSetting is the resolver for the createSetting field.
func (r *mutationResolver) CreateSetting(ctx context.Context, setting model.NewSetting) (*model.Setting, error) {
	insertedSetting := &model.Setting{
		Value: setting.Value,
		Key:   setting.Key,
	}

	if _, err := r.DB.NewInsert().Model(insertedSetting).Exec(ctx); err != nil {
		log.Printf("Failed to create setting: %v", err)
		return nil, err
	}

	return insertedSetting, nil
}

// DeleteSetting is the resolver for the deleteSetting field.
func (r *mutationResolver) DeleteSetting(ctx context.Context, keys []string) (int32, error) {
	result, err := r.DB.NewDelete().Model((*model.Setting)(nil)).Where("key IN (?)", bun.In(keys)).Exec(ctx)
	if err != nil {
		log.Printf("Failed to delete settings : %v", err)
		return 0, err
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		log.Printf("Failed to read affected rows: %v", err)
		return 0, err
	}

	return int32(rowsAffected), nil
}

// UpdateSetting is the resolver for the updateSetting field.
func (r *mutationResolver) UpdateSetting(ctx context.Context, setting model.NewSetting) (*model.Setting, error) {
	updateSetting := &model.Setting{
		Key:   setting.Key,
		Value: setting.Value,
	}

	if _, err := r.DB.NewUpdate().Model(updateSetting).Where("key = ?", setting.Key).Exec(ctx); err != nil {
		log.Printf("Failed to update setting %s: %v", setting.Key, err)
		return nil, err
	}

	return updateSetting, nil
}

// AddLabelToTicket is the resolver for the addLabelToTicket field.
func (r *mutationResolver) AddLabelToTicket(ctx context.Context, assignment []*model.NewLabelToTicketAssignment) (int32, error) {
	panic(fmt.Errorf("not implemented: AddLabelToTicket - addLabelToTicket"))
}

// RemoveLabelFromTicket is the resolver for the removeLabelFromTicket field.
func (r *mutationResolver) RemoveLabelFromTicket(ctx context.Context, labelName string, ticketID int32) (int32, error) {
	panic(fmt.Errorf("not implemented: RemoveLabelFromTicket - removeLabelFromTicket"))
}

// Tickets is the resolver for the tickets field.
func (r *queryResolver) Tickets(ctx context.Context, id []string, state []model.TicketState) ([]*model.Ticket, error) {
	panic(fmt.Errorf("not implemented: Tickets - tickets"))
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context, name []string) ([]*model.Label, error) {
	panic(fmt.Errorf("not implemented: Labels - labels"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, id []string, mail []string, role *model.UserRole) ([]*model.User, error) {
	var users []*model.User

	query := r.DB.NewSelect().Model(&users)

	if len(id) > 0 {
		query = query.Where("id IN (?)", bun.In(id))
	}
	if len(mail) > 0 {
		query = query.Where("mail IN (?)", bun.In(mail))
	}
	if role != nil {
		query = query.Where("role = ?", *role)
	}

	if err := query.Scan(ctx); err != nil {
		log.Printf("Failed to fetch users: %v", err)
		return nil, err
	}

	return users, nil
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context, keys []string) ([]*model.Setting, error) {
	var settings []*model.Setting

	query := r.DB.NewSelect().Model(&settings)

	if len(keys) > 0 {
		query = query.Where("key IN (?)", bun.In(keys))
	}

	if err := query.Scan(ctx); err != nil {
		log.Printf("Failed to get settings: %v", err)
		return nil, err
	}

	return settings, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
