query allTickets {
    tickets{
        id,
        originalTitle,
        title,
        text,
        note,
        state,
        createdAt,
        lastModified,
        labels {
            name,
            color,
            id
        }
    }
}

query ticketById ($id: [ID!]){
    tickets(id: $id){
        id,
        originalTitle,
        title,
        text,
        note,
        state,
        createdAt,
        lastModified,
        labels {
            name,
            color,
            id
        }
    }
}
