services:
  postgres:
    image: postgres:17
    container_name: database
    restart: unless-stopped
    env_file: .env.local
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: ghcr.io/fachschaftmathphysinfo/kummerkasten:latest
    env_file: .env.local
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started

volumes:
  pgdata: